Update Jenkinsfile

diff --git a/multi-stage-multi-agent/Jenkinsfile b/multi-stage-multi-agent/Jenkinsfile
--- a/multi-stage-multi-agent/Jenkinsfile
+++ b/multi-stage-multi-agent/Jenkinsfile
@@ -46,12 +46,21 @@ pipeline {
                 echo 'Visit http://<your-server-ip>:8888 in your browser to view the HTML page.'
             }
         }
+        
+        stage('Open Firewall Port') {
+            steps {
+                sh '''
+                    echo "Trying to open firewall port 8888"
+                    sudo ufw allow 8888 || echo "Cannot open port, check sudo permissions"
+                '''
+            }
+        }
 
         stage('Show Access Info') {
             steps {
                 sh '''
                     echo "🔗 Open this URL in your browser:"
-                    echo "http://$(curl -s ifconfig.me):8888"
+                    echo "http://$(hostname -I | awk '{print $1}'):8888"
                 '''
             }
         }
